# Generated by Django 5.2 on 2025-05-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0002_remove_posts_comments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
